### ISSUE TITLE
look like a type error

### ISSUE THREAD

**Issue by tlkao01** [DevifyPlatform/devify-cli#3]
Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }

**Comment by jollen** [comment]
I didn't understand about your issue description. What does "a type error" mean ?

**Comment by jollen** [comment]
(BTW. It looks that you have to be "root".)
